### ISSUE TITLE
Secret key in access_amherst_backend/access_amherst_backend/settings.py

### ISSUE THREAD

**Issue by TairanJ** [ac-i2i-engineering/access-amherst#4]
I was in the process of finalizing the Django framework when I noticed that the Django secret key is stored in settings.py and getting pushed to GitHub. It doesn't really matter right now, but this could cause us issues in the future when our code is in production, so I'm raising an issue in case there is something we want to do about it right now.

**Comment by liamjdavis** [comment]
Store the secret key in an environment variable in .env.

**Comment by DhyeyMavani2003** [comment]
Try to use `load_dotenv` and the like in python to access the creds and initialize them

**Comment by DhyeyMavani2003** [comment]
Closing this issue for now! Later we can add keys through custome environment settings or as mentioned above. Thanks for pointing it out early, but we don't need to worry about it for now!
