### ISSUE TITLE
RSS Feed Instead of Scrapping the Hub

### ISSUE THREAD

**Issue by TairanJ** [ac-i2i-engineering/access-amherst#7]
As I was looking at [the Hub](https://thehub.amherst.edu/events) to figure out how to scrape it, I discovered [a link titled RSS Feed](https://thehub.amherst.edu/events.rss) at the very bottom of the page. When you click it open, you'll see an automatically generated list of all public events between the time you click open the link and 1 month in the future in XML format (e.g., I clicked open the link at 1:02 AM on 10/6, and it provided me a link of all public events between 1:02 AM on 10/6 and 12:02 AM on 11/5). 

Getting information from this single HTML page is obviously much easier than scrapping the Hub, but the downside is that it only contains "public" events (i.e., events you can see without signing in); I have tried but was unable to find an RSS feed containing both public and private events. Still, I think it's worth switching from scrapping the Hub to parsing this RSS feed since we don't need the private events until we can figure out a sign-in page and we can probably ask IT for access to a private RSS feed (I'm not sure if IT has access to a private RSS feed, but since RSS feeds are generated automatically, I would assume so). Let me know what y'all think.

**Comment by liamjdavis** [comment]
I think it is definitely worth just scaping the RSS feed. I highly doubt that IT doesn't have some private RSS feed, so I think it will work just fine.

**Comment by TairanJ** [comment]
Sounds good!
